# A simple continuous deployment workflow for a linode VPS running a barebones nodejs backend app.

# Three steps:
# 1) actions/checkout -> copy updated code onto VPS
# 2) npm install  -> update dependencies
# 3) pm2 restart -> restart the app

# No build step currently needed. This simply updates the repository on the runner, updates any npm dependencies & restarts the app. 

# Workflow (activated on event) has several jobs, and each job has several steps.
name: Build node app

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: self-hosted # run on own VPS (nano-debbie)

        steps:
            # running actions
            - uses: actions/checkout@v3 # checkout my repo onto runner
            # - uses: actions/setup-node@v3 # installs node 16, exposing commands 'node' & 'npm' in PATH
            #   with:
            #       node-version: 16
            # running shell scripts
            - run: npm install
            - run: pm2 restart node_app  # uses pm2 npm module, which is running the node app, to restart app
