# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# Workflow (activated on event) has several jobs, and each job has several steps.
name: Build node app

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: self-hosted # run on own VPS (nano-debbie)

        steps:
            # running actions
            - uses: actions/checkout@v3 # checkout my repo onto runner
            # - uses: actions/setup-node@v3 # installs node 16, exposing commands 'node' & 'npm' in PATH
            #   with:
            #       node-version: 16
            # running shell scripts
            - run: npm install
